import Navbar from "./(shared)/Navbar";
import Footer from "./(shared)/Footer";
import "./globals.css";
// import { Inter } from 'next/font/google'
import { Rubik } from "next/font/google";
import Script from "next/script";
import { useState } from "react";
import { SelectedPage } from "./(shared)/types";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={rubik.className}>
      <body className="dark:bg-dark">
        <Script strategy="beforeInteractive">
          {`
            if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
              document.documentElement.classList.add('dark')
            } else {
              document.documentElement.classList.remove('dark')
            }
          `}
        </Script>

        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
